export const siteConfig = {
  creatorVideo: 'assets/author-intro.mp4',
  creatorPoster: 'assets/author-intro-poster.jpg',
};

export const english = {
  skip: 'Skip to content', navLabel:'Main navigation', navOverview:'Overview', navSensor:'The sensor', navDemo:'In action', navStory:'Our story', navAuthor:'Meet Leon',
  heroEyebrow:'A NEW PERSPECTIVE ON SQUASH TRAINING', heroTitle:'Every swing.<br><span>A deeper insight.</span>',
  heroDescription:'The movement of your racket. The motion of your body. Two perspectives, connected — to make the details of your training visible.',
  watchDemo:'Watch it in action', exploreSensor:'Explore the sensor', heroTech:'Dual sensing · Edge analysis',
  heroAlt:'SquashSense prototype mounted beside a player training on a squash court', heroVisualLabel:'BUILT FOR THE REAL COURT',
  heroCaption:'Sense motion. Understand your game.', heroCaptionSub:'SquashSense · Training research prototype', heroBottom:'From the end of your grip to the whole movement.', scrollExplore:'SCROLL TO EXPLORE',
  approachEyebrow:'ONE MOVEMENT. TWO PERSPECTIVES.', approachTitle:'See the body move.<br><span>Hear the racket speak.</span>',
  approachDescription:'The camera sees how your body moves. The racket sensor captures how your swing unfolds. SquashSense brings both signals together on ROCK 5C, placing each movement on a shared timeline.',
  stat1Title:'Racket motion sampling',stat1Description:'The ICM42688 six-axis sensor captures acceleration and angular velocity across three axes.',stat1Note:'DEFAULT FIRMWARE SAMPLE RATE',
  landmarksUnit:'points',stat2Title:'Human pose landmarks',stat2Description:'MediaPipe tracks the body’s skeleton to reveal joint angles and body rotation.',
  stat3Title:'Analysis at the edge',stat3Description:'A courtside computer connects the camera and wireless receiver, bringing motion signals and video together.',stat3Note:'SENSORS + VISION + SYNCHRONIZED REVIEW',
  pathSensor:'Racket sensor',pathCenter:'Sync · Fuse · Review',pathCamera:'Vision camera',pathCameraSmall:'Video → Pose landmarks',
  sensorEyebrow:'RACKET TRACKER · MOTION SENSOR',sensorTitle:'A small addition.<br><span>A new perspective.</span>',
  sensorDescription:'A custom cylindrical motion sensor, mounted at the end of the racket grip. Acceleration, angular velocity and relative orientation become clues you can return to after training.',
  installView:'INTERACTIVE INSTALLATION',canvasAlt:'3D installation schematic: a red and black squash racket with a tapered oval string bed, curved bridge and open triangular throat. A small cylindrical sensor moves toward and attaches to the butt end of its grip.',
  canvasLabel:'END OF THE GRIP. START OF THE INSIGHT.', installDisclaimer:'Conceptual shape and mounting position; not to scale.',replay:'Replay',sensorPhotoAlt:'Close-up of installing the circular motion sensor at the butt end of the racket grip',realPrototype:'ACTUAL PROTOTYPE',stepsLabel:'Installation steps',
  step1Title:'Align with the grip',step1Description:'Position the cylindrical sensor beneath the butt end.',step2Title:'Attach securely',step2Description:'Fit and secure the device to the end of the grip.',step3Title:'Hold still. Calibrate.',step3Description:'Keep still for sensor calibration, then record a neutral pose in the training interface.',
  sixAxis:'Six-axis motion sensing',wireless:'ESP-NOW wireless link',
  demoEyebrow:'REAL COURT. REAL TEST.',demoTitle:'One swing. <span>More of the picture.</span>',
  demoDescription:'From the skeleton overlay to racket motion signals and the training summary. Follow an actual test to see how SquashSense connects movement with data.',
  videoLabel:'SquashSense actual training demonstration',videoUnsupported:'Your browser does not support video playback.',playDemo:'Play training demonstration',videoPlayLabel:'Watch the field test',videoMeta:'FIELD TEST / ORIGINAL TRAINING INTERFACE',videoNote:'Values shown are from this recorded test.',videoError:'The video could not be played. Please try again.',
  insight1Title:'See the movement',insight1Description:'Skeleton overlays help you observe elbow, shoulder and knee angles, together with body rotation.',
  insight2Title:'Understand the swing',insight2Description:'From preparation and backswing to acceleration, follow-through and recovery, inertial signals help identify each phase.',
  insight3Title:'Return with perspective',insight3Description:'Review rhythm, movement sequencing and consistency across repeated swings on a synchronized timeline.',
  storyEyebrow:'BUILT, TESTED, REPEATED',storyTitle:'Built at the workbench.<br><span>Tested on the court.</span>',
  storyDescription:'Assembling hardware. Tuning signals. Stepping onto the court. SquashSense is an evolving training project, bringing sport and technology closer with every test.',
  assemblyAlt:'Assembling the computing and camera hardware inside its purple enclosure at a workbench',installationPhotoAlt:'Securing the sensor to the butt end of a squash racket grip on court',rockAlt:'Purple ROCK 5C camera unit mounted to the squash court glass',debuggingPhotoAlt:'Using a laptop at courtside to test and configure the racket sensor',
  gallery1Title:'An idea takes shape',gallery1Description:'Assembling and testing the computing and camera unit',gallery2Title:'Securing the grip-end sensor',gallery2Description:'Installing the grip-end sensor and testing the signal',gallery3Title:'Taking it to the court',gallery3Description:'Mounting the camera to capture the whole movement',gallery4Title:'Courtside equipment checks',gallery4Description:'Checking the sensor and training interface on a laptop',
  authorEyebrow:'MEET THE MAKER · LEON ON COURT',
  authorLeadAlt:'Leon focused on a shot during a squash match',authorPhotoLabel:'Leon on court',
  authorRole:'Squash player · Team captain · Creator of SquashSense',
  authorHeadline:'Ten years in the game. Still moving forward.',
  authorBiography:'Leon first picked up a squash racket at eight and has stayed committed to the sport ever since. Ten years on, he attends a U.S. boarding high school whose squash team has won the national championship in two consecutive seasons. Now serving as team captain, he continues to refine his game and work with his teammates toward new challenges and higher goals.',
  authorProject:'As the creator of SquashSense, Leon brings a decade of experience on court to the project. He is exploring how motion sensing and visual analysis can make the details of training easier to see and every review more informed.',
  authorGalleryTitle:'Focus, one swing at a time.',authorGalleryLabel:'LEON · ON COURT',
  authorFocusAlt:'Leon in a white squash shirt, racket ready and eyes on the ball',authorFocusCaption:'Eyes on the ball',
  authorRallyAlt:'Two squash players tracking the ball and preparing for the next shot',authorRallyCaption:'Between shots',
  authorBackswingAlt:'Leon lifting his racket in preparation for a shot during a match',authorBackswingCaption:'Preparing the swing',
  authorNextAlt:'Leon adjusting his position on court for the next shot',authorNextCaption:'Ready for what comes next',
  creatorAlt:'Leon introducing SquashSense with the camera and motion-sensing hardware',creatorEyebrow:'IN HIS OWN WORDS',
  creatorTitle:'The idea behind<br>SquashSense.',creatorDescription:'From experience on the court to racket sensing and visual analysis, hear Leon introduce SquashSense and the ideas behind the project.',
  creatorPlay:'Watch the introduction',creatorPlayAria:'Play Leon’s project introduction',creatorVideoLabel:'Leon’s project introduction',creatorVideoMeta:'PROJECT INTRODUCTION · LEON',creatorError:'The video could not be played. Please try again.',
  closingEyebrow:'SENSE THE MOTION. UNDERSTAND YOUR GAME.',closingTitle:'Make every swing <span>an insight.</span>',closingCta:'Back to the field test',footerText:'Sense every swing. See your progress.',backTop:'Back to top'
};
export const animationMessages = {
  zh: ['安装示意：将传感器对准拍柄末端。', '安装示意：传感器贴合并固定到拍柄底部。', '安装示意：静置校准后，在训练界面记录中立姿态。'],
  en: ['Installation: align the sensor with the grip end.', 'Installation: fit and secure the sensor.', 'Installation: calibrate while still, then record a neutral pose in the app.']
};
